server:
  port: 8090
spring:
  application:
    name: hw1v2-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
             - Path=/api/customers/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
             - Path=/api/orders/**
        - id: invoice-service
          uri: lb://INVOICE-SERVICE
          predicates:
             - Path=/api/invoices/**